# Generated by Django 3.2.25 on 2025-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250520_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(blank=True, choices=[('hammer', 'Hammer'), ('drill', 'Drill'), ('saw', 'Saw'), ('sander', 'Sander')], max_length=50, null=True),
        ),
    ]
