# Generated by Django 3.2.25 on 2025-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_variant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(
                default=False, help_text="Mark this product as a new arrival"
            ),
        ),
    ]
