# Generated by Django 3.2.25 on 2025-06-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_wishlistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_new",
        ),
    ]
