# Generated by Django 3.2.25 on 2025-06-20 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
